/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referring to this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Stampa\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icn-abierto-lig': '&#xe603;',
		'icn-acto-lig': '&#xe604;',
		'icn-alarma-lig': '&#xe605;',
		'icn-ampolleta-lig': '&#xe607;',
		'icn-archivo-lig': '&#xe608;',
		'icn-asterisco-lig': '&#xe609;',
		'icn-aviso-lig': '&#xe60c;',
		'icn-biblioteca-lig': '&#xe60d;',
		'icn-bower-lig': '&#xe60e;',
		'icn-calendario-lig': '&#xe60f;',
		'icn-camara-lig': '&#xe610;',
		'icn-caron-lig': '&#xe611;',
		'icn-casiopea-lig': '&#xe613;',
		'icn-cerrado-lig': '&#xe615;',
		'icn-ciclo-lig': '&#xe616;',
		'icn-circulo-lig': '&#xe617;',
		'icn-circulo-l-lig': '&#xe61d;',
		'icn-clip-lig': '&#xe61e;',
		'icn-codigo-lig': '&#xe61f;',
		'icn-compartir-lig': '&#xe624;',
		'icn-constel-lig': '&#xe628;',
		'icn-corazon-lig': '&#xe62a;',
		'icn-cruz-sur-lig': '&#xe62b;',
		'icn-cuadro-l-lig': '&#xe634;',
		'icn-cuadro-lig': '&#xe644;',
		'icn-descargar-lig': '&#xe645;',
		'icn-documento-lig': '&#xe67a;',
		'icn-email-lig': '&#xe67b;',
		'icn-engranaje-lig': '&#xe67c;',
		'icn-enlace-hor-lig': '&#xe67d;',
		'icn-enlace-lig': '&#xe67e;',
		'icn-equis-lig': '&#xe67f;',
		'icn-estorninos-lig': '&#xe680;',
		'icn-estrella-lig': '&#xe681;',
		'icn-etiqueta-lig': '&#xe682;',
		'icn-facebook-lig': '&#xe683;',
		'icn-flecha-lig': '&#xe684;',
		'icn-flickr-lig': '&#xe685;',
		'icn-grafico-lig': '&#xe686;',
		'icn-hedera-lig': '&#xe687;',
		'icn-hogar-lig': '&#xe688;',
		'icn-imagen-lig': '&#xe689;',
		'icn-impresora-lig': '&#xe68a;',
		'icn-ingresar-lig': '&#xe68b;',
		'icn-jekyll-lig': '&#xe68c;',
		'icn-lapiz-lig': '&#xe68d;',
		'icn-lentes-lig': '&#xe68e;',
		'icn-less-lig': '&#xe68f;',
		'icn-libro-lig': '&#xe690;',
		'icn-lupa-lig': '&#xe691;',
		'icn-lupa-mas-lig': '&#xe692;',
		'icn-lupa-menos-lig': '&#xe693;',
		'icn-mano-lig': '&#xe694;',
		'icn-mapa-conceptual-lig': '&#xe695;',
		'icn-mapa-lig': '&#xe696;',
		'icn-mapa-mas-lig': '&#xe697;',
		'icn-marcador-lig': '&#xe698;',
		'icn-mas-lig': '&#xe699;',
		'icn-menos-lig': '&#xe69a;',
		'icn-menu-lig': '&#xe69b;',
		'icn-movil-lig': '&#xe69c;',
		'icn-nav-lig': '&#xe69d;',
		'icn-noticias-lig': '&#xe69e;',
		'icn-ojo-lig': '&#xe69f;',
		'icn-orden-lig': '&#xe6a0;',
		'icn-palabra-lig': '&#xe6a1;',
		'icn-parlante-lig': '&#xe6a2;',
		'icn-anuncio-lig': '&#xe6a3;',
		'icn-parrafo-lig': '&#xe6a4;',
		'icn-pc-lig': '&#xe6a5;',
		'icn-perfil-lig': '&#xe6a6;',
		'icn-prohibir-lig': '&#xe6a7;',
		'icn-refrescar-lig': '&#xe6a8;',
		'icn-reloj-lig': '&#xe6a9;',
		'icn-rss-lig': '&#xe6aa;',
		'icn-salir-lig': '&#xe6ab;',
		'icn-ese-lig': '&#xe6ac;',
		'icn-soundcloud-lig': '&#xe6ad;',
		'icn-stampa-lig': '&#xe6ae;',
		'icn-subir-lig': '&#xe6af;',
		'icn-tablet-lig': '&#xe6b0;',
		'icn-tiempo-lig': '&#xe6b1;',
		'icn-trabajo-lig': '&#xe6b2;',
		'icn-travesia-lig': '&#xe6b3;',
		'icn-twitter-lig': '&#xe6b4;',
		'icn-usuario-admin-lig': '&#xe6b5;',
		'icn-usuario-lig': '&#xe6b6;',
		'icn-usuario-mas-lig': '&#xe6b7;',
		'icn-usuario-menos-lig': '&#xe6b8;',
		'icn-usuarios-lig': '&#xe6b9;',
		'icn-vimeo-lig': '&#xe6ba;',
		'icn-vinculo-lig': '&#xe6bb;',
		'icn-vineta-lig': '&#xe6bc;',
		'icn-visto-lig': '&#xe6bd;',
		'icn-youtube-lig': '&#xe6be;',
		'icn-parlante': '&#xe602;',
		'icn-lentes': '&#xe60a;',
		'icn-youtube': '&#xe61b;',
		'icn-libro': '&#xe61c;',
		'icn-cruz-sur': '&#xe606;',
		'icn-menu': '&#xe678;',
		'icn-perfil': '&#xe675;',
		'icn-tablet': '&#xe674;',
		'icn-pc': '&#xe676;',
		'icn-movil': '&#xe677;',
		'icn-estorninos': '&#xe679;',
		'icn-usuario': '&#xe63a;',
		'icn-usuarios': '&#xe66e;',
		'icn-usuario-menos': '&#xe66f;',
		'icn-usuario-mas': '&#xe670;',
		'icn-admin': '&#xe673;',
		'icn-prohibir': '&#xe671;',
		'icn-bower': '&#xe672;',
		'icn-vimeo': '&#xe620;',
		'icn-stampa': '&#xe621;',
		'icn-soundcloud': '&#xe622;',
		'icn-anuncio': '&#xe623;',
		'icn-less': '&#xe625;',
		'icn-jekyll': '&#xe626;',
		'icn-flickr': '&#xe627;',
		'icn-caron-der': '&#xe629;',
		'icn-camara': '&#xe62c;',
		'icn-burbuja': '&#xe62d;',
		'icn-subir': '&#xe619;',
		'icn-circulo': '&#xe618;',
		'icn-mano-der': '&#xe60b;',
		'icn-cuadro-l': '&#xe612;',
		'icn-circulo-l': '&#xe614;',
		'icn-vineta': '&#xe62f;',
		'icn-vinculo': '&#xe630;',
		'icn-twitter': '&#xe631;',
		'icn-trabajo': '&#xe632;',
		'icn-tiempo': '&#xe633;',
		'icn-ese': '&#xe635;',
		'icn-salir': '&#xe636;',
		'icn-rss': '&#xe637;',
		'icn-reloj': '&#xe638;',
		'icn-refrescar': '&#xe639;',
		'icn-parrafo': '&#xe63b;',
		'icn-orden-hor': '&#xe63d;',
		'icn-ojo': '&#xe63e;',
		'icn-noticias': '&#xe63f;',
		'icn-marcador': '&#xe640;',
		'icn-mapa': '&#xe641;',
		'icn-mapa-mas': '&#xe643;',
		'icn-mapa-conceptual': '&#xe642;',
		'icn-lupa': '&#xe646;',
		'icn-lupa-menos': '&#xe647;',
		'icn-lupa-mas': '&#xe648;',
		'icn-lapiz': '&#xe649;',
		'icn-ingresar': '&#xe64a;',
		'icn-impresora': '&#xe64b;',
		'icn-imagen': '&#xe64c;',
		'icn-hogar': '&#xe64d;',
		'icn-hedera': '&#xe64e;',
		'icn-grafico': '&#xe64f;',
		'icn-flecha-der': '&#xe650;',
		'icn-facebook': '&#xe651;',
		'icn-etiqueta': '&#xe652;',
		'icn-estrella': '&#xe653;',
		'icn-equis': '&#xe654;',
		'icn-enlace': '&#xe655;',
		'icn-enlace-hor': '&#xe656;',
		'icn-engranaje': '&#xe657;',
		'icn-email': '&#xe658;',
		'icn-documento': '&#xe659;',
		'icn-descargar': '&#xe65a;',
		'icn-cuadro': '&#xe65b;',
		'icn-mas': '&#xe65c;',
		'icn-menos': '&#xe61a;',
		'icn-corazon': '&#xe65d;',
		'icn-constel': '&#xe65e;',
		'icn-compartir': '&#xe65f;',
		'icn-codigo': '&#xe660;',
		'icn-clip': '&#xe661;',
		'icn-ciclo': '&#xe662;',
		'icn-casiopea': '&#xe663;',
		'icn-cerrado': '&#xe664;',
		'icn-abierto': '&#xe665;',
		'icn-calendario': '&#xe666;',
		'icn-biblioteca': '&#xe667;',
		'icn-asterisco': '&#xe668;',
		'icn-archivo': '&#xe669;',
		'icn-ampolleta': '&#xe66a;',
		'icn-alarma': '&#xe66b;',
		'icn-aviso': '&#xe66c;',
		'icn-acto': '&#xe66d;',
		'icn-travesia': '&#xe600;',
		'icn-nav-der': '&#xe601;',
		'icn-visto': '&#xe62e;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icn-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
